{
 "title": "CPU Utilization Details (Cores)1",
 "description": "This is an dashboard for which provides CPU utilization details for multi-core systems.  It allows to easily see if overall CPU usage is high or if there are overloaded cores. Designed to be used with node-exporter >=0.16.0, as node_cpu is now renamed to node_cpu_seconds_total. forked from percona",
 "tags": [
  "Enway",
  "CPU"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_cpu_seconds_total\", job!=\"prometheus\"}, instance)"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "label_values(node_cpu_seconds_total{instance=\"$host\"}, cpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$host - Overall CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "$host - Current CPU Core Utilization",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "clamp_max(avg by () (sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Avg"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Overall CPU Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Cores - total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - user",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"user\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - system",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"system\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - iowait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - steal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "All Cores - other",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "CPU Cores Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Per Core CPU Usage",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
     "content": "Per CPU usage Information shows  usage for each CPU (Virtual) core.  The Current (most recent) numbers are shown together with history as sparkline"
    }
   ]
  },
  {
   "title": "Per Core Usage Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "cpu",
   "targets": [
    {}
   ]
  },
  {
   "title": "$cpu - total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by () (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - user",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"user\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - system",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"system\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - iowait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"iowait\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - steal",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max( (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  },
  {
   "title": "$cpu - other",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(sum by (instance) (avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100,100)"
    }
   ]
  }
 ]
}